### PR TITLE
Fix Backend-Error when trying to delete a participant from non-existing Elastic-Index

### LINKED ISSUE #282: Issue with clicking "Delete incl. data" button on Participant page
Clicking on "Delete incl. data" to remove participants causes an issue on the develop branch. The participant is only removed from the list after refreshing the page. This functionality works correctly on the main and staging branches.

delete_participant

### PR DESCRIPTION
**Pull request by ja-fra**
The Index is auto-created, so we should not care for non-existing indexes.

----
Closes #282

### CODE REVIEW

File: studymanager/src/main/java/io/redlink/more/studymanager/service/ElasticService.java [hunk 1]
```diff
@@ -368,4 +371,32 @@ private Map<String, Object> toData(Map<String, Object> source) {
...
+        return ElasticService.handleIndexNotFoundException(e, supplier, Function.identity());
+    }
+
+    private static <R, E extends Exception, T extends Exception> R handleIndexNotFoundException(E e, Supplier<R> supplier, Function<E, T> exceptionTFunction) throws T {
+        if (isElasticIndexNotFound(e)) return supplier.get();
+        throw exceptionTFunction.apply(e);
+    }
+
+    private static boolean isElasticIndexNotFound(Exception e) {
+        if (e instanceof ElasticsearchException ee) {
```
Comment (benitsch) [inline studymanager/src/main/java/io/redlink/more/studymanager/service/ElasticService.java:385]: Why are there two different if conditions? You can combine these into one with &&.

**Review by benitsch — APPROVED** [review]

File: studymanager/src/main/java/io/redlink/more/studymanager/service/ElasticService.java (hunk 1 above)
Comment (ja-fra) [reply studymanager/src/main/java/io/redlink/more/studymanager/service/ElasticService.java:385]: True, but I find this way better readable.
